server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

jwt.secret=${JWT_SECRET}

spring.web.cors.allowed-origins=https://your-app.vercel.app

#spring.data.redis.host=${REDIS_HOST}
#spring.data.redis.port=${REDIS_PORT}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
cookie.secure = true
cookie.same-site = None

firebase.config=${FIREBASE_CONFIG:}