spring.datasource.url=jdbc:postgresql://localhost:5432/shalom_local
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=validate

jwt.secret=this-is-test-secret-key-change-me-please-very-long-abcdefg-1234567890

spring.data.redis.host=localhost
spring.data.redis.port=6379

cors.allowed-origins=http://localhost:5173,http://172.30.1.9:5173
cookie.secure = false
cookie.same-site = Lax